/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Users;
import java.awt.event.ActionListener;
import javax.swing.Icon;

/**
 *
 * @author Keyla
 */
public class Record extends javax.swing.JFrame {

    /**
     * Creates new form Record
     */
    public Record() {
        initComponents();
    }
    
    public void escuchar(ActionListener manejador){
        btnIniciarSesion.addActionListener(manejador);
        btnRegistro.addActionListener(manejador);
        radioAdmin.addActionListener(manejador);
        radioEmpleado.addActionListener(manejador);
    }
    
    public Users getUser(){
        String name = txtName.getText();
        int iduser = Integer.parseInt(txtIDUser.getText());
        String password = txtPassword.getText();
        String email = txtEmail.getText();
        this.profile.getSelection();
        
        return new Users(iduser, name, password, email, profile);
    }
    
    public void limpiar(){
        txtEmail.setText("");
        txtIDUser.setText("");
        txtName.setText("");
        txtPassword.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profile = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        txtIDUser = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        radioAdmin = new javax.swing.JRadioButton();
        radioEmpleado = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnRegistro = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnIniciarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 220, 30));

        txtIDUser.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(txtIDUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 220, 30));

        txtPassword.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 220, 30));

        txtEmail.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 220, 30));

        profile.add(radioAdmin);
        radioAdmin.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        radioAdmin.setText("Admin");
        jPanel2.add(radioAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        profile.add(radioEmpleado);
        radioEmpleado.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        radioEmpleado.setText("Employee");
        jPanel2.add(radioEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/7238996_basic_name_office_business_management_icon (2).png"))); // NOI18N
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setOpaque(true);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 30, 30));

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/309035_user_account_human_person_icon.png"))); // NOI18N
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel2.setOpaque(true);
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 30, 30));

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/9055383_bxs_lock_icon.png"))); // NOI18N
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel3.setOpaque(true);
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 30, 30));

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1181190_email_gmail_google_mail_icon (1).png"))); // NOI18N
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel4.setOpaque(true);
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 30, 30));

        btnRegistro.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnRegistro.setText("SING UP");
        btnRegistro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 230, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Already have an account?");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, 20));

        btnIniciarSesion.setText("Sing In");
        jPanel2.add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.ButtonGroup profile;
    private javax.swing.JRadioButton radioAdmin;
    private javax.swing.JRadioButton radioEmpleado;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIDUser;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables
}
